from collections import OrderedDict
import numpy as np

CATEGORIES = OrderedDict({
    1: 'person',
    2: 'bicycle',
    3: 'car',
    4: 'motorcycle',
    5: 'airplane',
    6: 'bus',
    7: 'train',
    8: 'truck',
    9: 'boat',
    10: 'traffic light',
    11: 'fire hydrant',
    13: 'stop sign',
    14: 'parking meter',
    15: 'bench',
    16: 'bird',
    17: 'cat',
    18: 'dog',
    19: 'horse',
    20: 'sheep',
    21: 'cow',
    22: 'elephant',
    23: 'bear',
    24: 'zebra',
    25: 'giraffe',
    27: 'backpack',
    28: 'umbrella',
    31: 'handbag',
    32: 'tie',
    33: 'suitcase',
    34: 'frisbee',
    35: 'skis',
    36: 'snowboard',
    37: 'sports ball',
    38: 'kite',
    39: 'baseball bat',
    40: 'baseball glove',
    41: 'skateboard',
    42: 'surfboard',
    43: 'tennis racket',
    44: 'bottle',
    46: 'wine glass',
    47: 'cup',
    48: 'fork',
    49: 'knife',
    50: 'spoon',
    51: 'bowl',
    52: 'banana',
    53: 'apple',
    54: 'sandwich',
    55: 'orange',
    56: 'broccoli',
    57: 'carrot',
    58: 'hot dog',
    59: 'pizza',
    60: 'donut',
    61: 'cake',
    62: 'chair',
    63: 'couch',
    64: 'potted plant',
    65: 'bed',
    67: 'dining table',
    70: 'toilet',
    72: 'tv',
    73: 'laptop',
    74: 'mouse',
    75: 'remote',
    76: 'keyboard',
    77: 'cell phone',
    78: 'microwave',
    79: 'oven',
    80: 'toaster',
    81: 'sink',
    82: 'refrigerator',
    84: 'book',
    85: 'clock',
    86: 'vase',
    87: 'scissors',
    88: 'teddy bear',
    89: 'hair drier',
    90: 'toothbrush'
})

# 0 for background
CONSECUTIVE_ID_2_CAT_ID = np.array([0] + list(CATEGORIES.keys()))

CAT_ID_2_CONSECUTIVE_ID = dict(zip(CONSECUTIVE_ID_2_CAT_ID, range(len(CONSECUTIVE_ID_2_CAT_ID))))


CXR_ID_2_NAME = OrderedDict({
    1:  'No finding',
    2:  'Cardiomegaly',
    3:  'Lung opacity',
    4:  'Edema',
    5:  'Consolidation',
    6:  'Atelectasis',
    7:  'Pneumothorax',
    8:  'Pleural effusion',
    9:  'Aortic enlargement',
    10: 'ILD',
    11: 'Infiltration',
    12: 'Nodule/Mass',
    13: 'Pulmonary fibrosis',
    14: 'Pleural thickening',
    15: 'Calcification',
    16: 'Other lesion',
    17: 'Pneumonia',
    18: 'Tuberculosis',
    19: 'Lung tumor',
    20: 'Other disease',
    21: 'COPD',
    22: 'Emphysema',
    23: 'Enlarged PA',
    24: 'Lung cyst',
    25: 'Mediastinal shift',
    26: 'Lung cavity',
    27: 'Rib fracture',
    28: 'Clavicle fracture'
})
CXR_CONS_ID_2_ID = np.array(list(CXR_ID_2_NAME.keys()))
CXR_ID_2_CONS_ID = dict(zip(CXR_CONS_ID_2_ID, range(len(CXR_CONS_ID_2_ID))))